server.port=8080
spring.application.name=SecureCode Analyzer

gemini.api.key=${GEMINI_API_KEY}

spring.servlet.multipart.max-file-size=512KB
spring.servlet.multipart.max-request-size=512KB
scanner.max-code-length=50000

scanner.rate-limit.requests-per-minute=5

scanner.cors.allowed-origins=http://localhost:3000

